version: "3.8"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todolist
      MYSQL_USER: todolist
      MYSQL_PASSWORD: secret
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - db
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8989:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./project:/var/www
      - app_cache:/var/www/var/cache
    restart: always
    networks:
      - dev

  blackfire:
    image: blackfire/blackfire
    container_name: black_docker_symfony
    ports: [ "8707" ]
    environment:
      # Exposes BLACKFIRE_\* environment variables from the host
      BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
    networks:
      - dev

volumes:
  db_data: {}
  app_cache: {}

networks:
  dev:
