<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEh2wfvn\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEh2wfvn/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEh2wfvn.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEh2wfvn\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerEh2wfvn\appTestDebugProjectContainer([
    'container.build_hash' => 'Eh2wfvn',
    'container.build_id' => 'b7260ae1',
    'container.build_time' => 1663694369,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEh2wfvn');
