<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMusSkb3\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMusSkb3/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerMusSkb3.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerMusSkb3\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerMusSkb3\App_KernelProdContainer([
    'container.build_hash' => 'MusSkb3',
    'container.build_id' => '3383ba34',
    'container.build_time' => 1665495065,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMusSkb3');
