<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin_tasks' => [[], ['_controller' => 'App\\Controller\\Admin\\Task\\IndexController::index'], [], [['text', '/admin/tasks']], [], [], []],
    'admin_user_edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\User\\EditController::editUser'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/users']], [], [], []],
    'user_list' => [[], ['_controller' => 'App\\Controller\\Admin\\User\\IndexController::listAction'], [], [['text', '/admin/users']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\DefaultController::indexAction'], [], [['text', '/']], [], [], []],
    'task_create' => [[], ['_controller' => 'App\\Controller\\Task\\CreateController::createAction'], [], [['text', '/tasks/create']], [], [], []],
    'task_delete' => [['id'], ['_controller' => 'App\\Controller\\Task\\DeleteController::deleteTaskAction'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'task_edit' => [['id'], ['_controller' => 'App\\Controller\\Task\\EditController::editAction'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'task_list' => [[], ['_controller' => 'App\\Controller\\Task\\IndexController::listAction'], [], [['text', '/tasks']], [], [], []],
    'task_toggle' => [['id'], ['_controller' => 'App\\Controller\\Task\\ToggleController::toggleTaskAction'], [], [['text', '/toggle'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\User\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\User\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'user_create' => [[], ['_controller' => 'App\\Controller\\User\\RegistrationController::register'], [], [['text', '/users/create']], [], [], []],
];
