<?php

namespace ContainerMusSkb3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\Task\IndexController' shared autowired service.
     *
     * @return \App\Controller\Admin\Task\IndexController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\Task\\IndexController'] = $instance = new \App\Controller\Admin\Task\IndexController(($container->privates['App\\Repository\\TaskRepository'] ?? $container->load('getTaskRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\Admin\\Task\\IndexController', $container));

        return $instance;
    }
}
