<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEiqmluc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEiqmluc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEiqmluc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEiqmluc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEiqmluc\appProdProjectContainer([
    'container.build_hash' => 'Eiqmluc',
    'container.build_id' => 'd768fae2',
    'container.build_time' => 1663435089,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEiqmluc');
