<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBrodqlo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBrodqlo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBrodqlo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBrodqlo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBrodqlo\appDevDebugProjectContainer([
    'container.build_hash' => 'Brodqlo',
    'container.build_id' => '5eddd41d',
    'container.build_time' => 1663694554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBrodqlo');
