<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLtVO1xC\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLtVO1xC/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLtVO1xC.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLtVO1xC\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLtVO1xC\App_KernelTestDebugContainer([
    'container.build_hash' => 'LtVO1xC',
    'container.build_id' => '4a1421e1',
    'container.build_time' => 1666033990,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLtVO1xC');
