From php:8.1-apache

Run echo "ServerName localhost">> /etc/apache2/apache2.conf

Run apt-get update \
  && apt-get install -y --no-install-recommends apt-utils zip libzip-dev


RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
  mv composer.phar /usr/local/bin/composer

COPY ./config/app.php.ini /usr/local/etc/php/conf.d/



RUN docker-php-ext-install pdo pdo_mysql zip opcache

COPY ./config/opcache.ini /usr/local/etc/php/conf.d

RUN pecl install apcu && docker-php-ext-enable apcu

RUN pecl install xdebug \
  && docker-php-ext-enable xdebug\
  && echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/xdebug.ini


RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
  && architecture=$(uname -m) \
  && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/$architecture/$version \
  && mkdir -p /tmp/blackfire \
  && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
  && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so \
  && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8307\n" > $PHP_INI_DIR/conf.d/blackfire.ini \
  && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz

WORKDIR /var/www/
