From php:8.1-apache

Run echo "ServerName localhost">> /etc/apache2/apache2.conf

Run apt-get update \
  && apt-get install -y --no-install-recommends apt-utils zip libzip-dev


RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
  mv composer.phar /usr/local/bin/composer

COPY ./config/app.php.ini /usr/local/etc/php/conf.d/

RUN docker-php-ext-install pdo pdo_mysql zip

WORKDIR /var/www/
